prgrms-web-devcourse-final-project/WEB5_6_9to6_BE

src/main/java/com/grepp/spring/app/controller/api/ChatController.java

목업 서버에 올라갈 ChatController 리팩토링 진행했습니다.

Refactor: chatcontroller

---

docker-compose.yml
src/main/java/com/grepp/spring/app/controller/api/QuizController.java

서바이벌 목록 조회
서바이벌 일정 조회
서바이벌 주차별 결과 등록 
컨트롤러 완성  했습니다.
그런데 이거 스터디 쪽으로 넘기는 게 맞는 거 같습니다. path만 달라서 그냥 코드만 스터디 컨트롤러 쪽으로 옮기면 될 듯 합니다.

refactor:퀴즈 컨트롤러 구현 완료

---

src/main/java/com/grepp/spring/app/controller/api/StudyController.java

- 출석체크
- 스터디 목록(검색)
- 스터디 정보 조회
- 스터디 정보 수정
- 스터디 신청 목록 조회
- 유저가 스터디 맴버인지 조회
- 스터디 신청 목록 조회
- 스터디 맴버 조회
- 스터디 생성
- 스터디 목표 조회
- 스터디 목표 달성
생성, 수정, 검증에 대한 요청은 모두 성공처리로 반환하며 데이터를 저장하지 않고 있는 상태입니다.

Refactor: study controller 완료

---

src/main/java/com/grepp/spring/app/controller/api/MemberController.java

Fix: swagger 오류 수정

---

src/main/java/com/grepp/spring/app/controller/api/StudyController.java
src/main/java/com/grepp/spring/infra/response/CommonResponse.java
src/main/java/com/grepp/spring/infra/response/SuccessCode.java

- id 타입을 long으로 변경하였습니다.
- CommonResponse에 각 요청별 성공메시지를 변경할 수 있게 noContent를 오버로딩하여 만들고 SuccessMessage enum클래스도 만들었습니다.

Refactor : study controller id 타입 변경 및 CommonResponse 수정

---

src/main/java/com/grepp/spring/app/controller/api/AlarmController.java

- id 타입을 int -> long으로 변경하였습니다
- 반환값을 Map.of에서 공통응답객체 CommonResponse로 변경하였습니다.

Refactor: alarm controller id 타입 변경 및 공통응답객체 사용

---

src/main/java/com/grepp/spring/app/controller/api/MemberController.java

Feat: 유저 정보 요청에 point 추가

---

src/main/java/com/grepp/spring/app/controller/api/AlarmController.java

Refactor: alarm controller 빈칸 추가

---

src/main/java/com/grepp/spring/app/controller/api/RewardController.java

서버에 전체 이미지를 저장하는 api 추가
서버에서 전체 이미지를 받아오는api 추가

feat:api 추가

---

src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
src/main/java/com/grepp/spring/app/model/auth/dto/VerifyCodeCheckResponse.java
src/main/java/com/grepp/spring/infra/error/RestApiExceptionAdvice.java

현재 mockup 서버에서 코드가 제대로 실행되지 않아 현재 실행되는 코드인 제 브랜치의 코드를 머지하겠습니다.

Refactor: mockup 코드 변경

---

src/main/resources/application-prod.properties
src/main/resources/application.properties

배포 환경에서 Oauth2 소셜 로그인이 동작하지 않는 설정 문제를 해결

Chore: oauth2 관련 설정변경 (mock)

---

src/main/java/com/grepp/spring/app/controller/api/timer/TimerController.java
src/main/java/com/grepp/spring/app/model/timer/dto/DailyStudyLogResponse.java
src/main/java/com/grepp/spring/app/model/timer/dto/StudyWeekTimeResponse.java
src/main/java/com/grepp/spring/app/model/timer/dto/TotalStudyTimeResponse.java
src/main/java/com/grepp/spring/app/model/timer/repository/TimerQueryRepository.java
src/main/java/com/grepp/spring/app/model/timer/service/TimerService.java

- DailyStudyLogResponse 변수명 변경
- getAllTimer 반환 DTO 생성
- 스터디별 지난 7일간 공부시간 -> 누적, 일별 구현
- 타이머 등록
- 특정 스터디에서 지난 7일간 일별 공부시간
- 특정 스터디에서 지난 7일간 누적 공부시간
- 전체 스터디에 대해 누적 공부시간
- ~~현재 페이지 상 스터디별 공부 시간은 누적이지만 혹시 몰라 일별로 반환하도록했습니다.~~
- 그냥 둘 다 만들었습니다.

Refactor: 타이머 전체 누적 시간 조회 DTO 반환, DailyStudyLogResponse 반환 변수명 변경

---

src/main/java/com/grepp/spring/app/controller/api/ChatController.java
src/main/java/com/grepp/spring/app/controller/api/RewardController.java
src/main/java/com/grepp/spring/app/controller/api/alarm/AlarmController.java
src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
src/main/java/com/grepp/spring/app/controller/api/study/StudyController.java
src/main/java/com/grepp/spring/app/controller/api/timer/TimerController.java

스웨거 한글 명세서를 작성했습니다.
git으로 브랜치 받아서 본인 파트 확인해주세요.

Doc: swagger

---

build.gradle
src/main/java/com/grepp/spring/app/model/quiz/entity/Choice.java
src/main/java/com/grepp/spring/app/model/quiz/entity/Quiz.java
src/main/resources/application.properties

Fix: entity 충돌 오류 수정했습니다

---

src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2SuccessHandler.java
src/main/resources/application-prod.properties

소셜 로그인 시 기존 유저의 경우 루트 경로로 리다이랙트 되었는데 이 경로는 프론트 메인 경로로 변경하였습니다.

Refactor: 기존 소셜 로그인 리다이랙트 주소를 프론트 서버 주소로 변경하였습니다.

---

src/main/java/com/grepp/spring/app/controller/api/timer/TimerController.java
src/main/java/com/grepp/spring/app/model/member/repository/StudyMemberRepository.java

다른 맴버의 id도 조회할 수 있도록 Query Parameter로 memberId를 받도록 변경했습니다.
해당 로직의 studyMemberId 찾기 쿼리 중 Param으로 studyId가 아닌 studyMemberId를 사용하는 문제가 있어 고쳐두었습니다.(부끄럽네요;;)

Refactor: api uri 변경

---

src/main/java/com/grepp/spring/app/model/study/repository/StudyMemberRepositoryCustomImpl.java
src/main/java/com/grepp/spring/app/model/study/service/StudyService.java

Hotfix: 스터디 맴버 조회 인가 로직 취소

---

src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

현재 로그인을 하지 않는다면 스웨거에 진입이 어려울 겁니다.
추가적으로 소셜로그인 관련 엔드포인트도 풀어두었습니다.
**스웨거 관련 엔드포인트는 실제 배포전에는 무조건 주석처리 또는 지워야합니다.**

Hotfix: oauth2, 스웨거 권한 처리

---

src/main/java/com/grepp/spring/app/controller/api/alarm/AlarmController.java
src/main/java/com/grepp/spring/app/model/alarm/service/AlarmService.java
src/main/java/com/grepp/spring/app/model/alarm/sse/EmitterRepository.java

- SSE 구독 시 CORS 오류가 발생하는데 SSE timeout 때문에 발생하는 것 같아 타임아웃 방지 코드를 추가했습니다.
- 안정적인 연결 유지를 위해 30초 간격 heartbeat 이벤트 전송 기능을 추가했습니다.

Hotfix: SSE 타임아웃 방지 추가

---

src/main/java/com/grepp/spring/app/controller/api/QuizController.java
src/main/java/com/grepp/spring/app/model/quiz/service/QuizCreateService.java
src/main/java/com/grepp/spring/app/model/quiz/service/QuizGetService.java
src/main/java/com/grepp/spring/app/model/quiz/service/QuizGradingService.java
src/main/java/com/grepp/spring/app/model/quiz/service/QuizSchedulingService.java
src/main/java/com/grepp/spring/app/model/quiz/service/SurvivalResultService.java
src/test/java/com/grepp/spring/app/model/quiz/service/QuizGetServiceTest.java

주석으로 간단하게 로직 설명, 컨벤션에 맞지 않는 메서드 이름 수정,  zone = "Asia/Seoul" 명시적으로 적었습니다# 📌 과제 설명 
주석으로 간단하게 로직 설명, 컨벤션에 맞지 않는 메서드 이름 수정, 직관적이 않은 코드 줄 바꿈 하였으며 zone = "Asia/Seoul" 명시적으로 적었습니다
로직 변경사항은 없습니다

feat: 주석으로 설명 추가 및 zone = "Asia/Seoul" 추가

---

src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
src/main/java/com/grepp/spring/app/model/study/service/StudyMemberService.java
src/main/java/com/grepp/spring/app/model/study/service/StudyService.java

목표달성 시 100포인트가 지급되도록 로직을 수정했습니다.
출석 체크 시 포인트 지급을 100에서 10으로 변경하였습니다.
목표달성 시 memberRepository.addRewardPoints(memberId, 100)를 통해 해당 맴버에게 100포인트를 지급하도록 하였습니다.
테스트 계정은 user3@example.com이고 기존 포인트는 340, studyId 1 스터디에 대해 goalId 1을 달성 등록 후 포인트가 440이 되는 것을 확인 하였고 중복등록 시 예외가 발생하여 추가적인 포인트 지급이 되지않는 것을 확인하였습니다.
추가적으로 applyToStudy가 로직과 의미가 맞지 않는 것같아 enrollInStudy로 변경하였습니다.

Feat: 목표 달성 시 100 포인트 지급

---

src/main/java/com/grepp/spring/app/model/member/entity/Member.java
src/main/java/com/grepp/spring/app/model/study/service/StudyService.java

생각해보니 서바이벌 우승자에게 point는 주는데 wincount는 안 올려줘서 wincount++ 로직 추가했습니다

Feat: 서바이벌 스터디 우승자 winCount 증가
